import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "../components/ui/ToastProvider";
import { ConfirmProvider } from "../components/ui/ConfirmProvider";
import NotifikasiPatroliListener from "../components/NotifikasiPatroliListener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 💡 PWA VIEWPORT: Mengatur warna atas browser HP
export const viewport: Viewport = {
  themeColor: "#e53e3e",
};

// 💡 PWA METADATA: Mendaftarkan manifest dan dukungan install iOS
export const metadata: Metadata = {
  title: "SIBM",
  description: "Generated by SIBM MKS 2026",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "SIBM",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ToastProvider>
          <ConfirmProvider>
            <NotifikasiPatroliListener />
            {children}
          </ConfirmProvider>
        </ToastProvider>
      </body>
    </html>
  );
}