import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "../components/ui/ToastProvider";
import { ConfirmProvider } from "../components/ui/ConfirmProvider";
import NotifikasiPatroliListener from "../components/NotifikasiPatroliListener";
import NotifikasiKendaraanListener from "../components/NotifikasiKendaraanListener";
import InstallPrompt from "../components/InstallPrompt";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Font tema admin "Bento Hangat" (src/components/admin/admin-theme.css). preload dimatikan
// supaya halaman staf/portal yang tidak memakainya tidak ikut mengunduh font ini.
const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
  preload: false,
});

// 💡 PWA VIEWPORT: Mengatur warna atas browser HP
export const viewport: Viewport = {
  themeColor: "#a3122a",
};

// 💡 PWA METADATA: Mendaftarkan manifest dan dukungan install iOS
export const metadata: Metadata = {
  title: "SIBM",
  description: "Generated by SIBM MKS 2026",
  manifest: "/manifest.json",
  // Favicon & ikon iOS dari public/icons (dibuat scripts/generate-icons.mjs dari logogram Samudera).
  // Ikon iOS "Add to Home Screen" harus kotak penuh tanpa transparansi -- iOS membulatkan sendiri.
  icons: {
    icon: [{ url: "/icons/favicon-48.png", type: "image/png", sizes: "48x48" }],
    apple: "/icons/apple-touch-icon.png",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "SIBM",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${plusJakarta.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ToastProvider>
          <ConfirmProvider>
            <NotifikasiPatroliListener />
            <NotifikasiKendaraanListener />
            {children}
            <InstallPrompt />
          </ConfirmProvider>
        </ToastProvider>
      </body>
    </html>
  );
}